/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PackingListRouteImport } from './routes/packing-list'
import { Route as ScorecardsRouteImport } from './routes/scorecards'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as SlanderRouteImport } from './routes/slander'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingListRoute = PackingListRouteImport.update({
  id: '/packing-list',
  path: '/packing-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardsRoute = ScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const SlanderRoute = SlanderRouteImport.update({
  id: '/slander',
  path: '/slander',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/packing-list': typeof PackingListRoute
  '/scorecards': typeof ScorecardsRoute
  '/scores': typeof ScoresRoute
  '/slander': typeof SlanderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/packing-list': typeof PackingListRoute
  '/scorecards': typeof ScorecardsRoute
  '/scores': typeof ScoresRoute
  '/slander': typeof SlanderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/packing-list': typeof PackingListRoute
  '/scorecards': typeof ScorecardsRoute
  '/scores': typeof ScoresRoute
  '/slander': typeof SlanderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/draw'
    | '/gallery'
    | '/leaderboard'
    | '/packing-list'
    | '/scorecards'
    | '/scores'
    | '/slander'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/courses'
    | '/draw'
    | '/gallery'
    | '/leaderboard'
    | '/packing-list'
    | '/scorecards'
    | '/scores'
    | '/slander'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/draw'
    | '/gallery'
    | '/leaderboard'
    | '/packing-list'
    | '/scorecards'
    | '/scores'
    | '/slander'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CoursesRoute: typeof CoursesRoute
  DrawRoute: typeof DrawRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PackingListRoute: typeof PackingListRoute
  ScorecardsRoute: typeof ScorecardsRoute
  ScoresRoute: typeof ScoresRoute
  SlanderRoute: typeof SlanderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing-list': {
      id: '/packing-list'
      path: '/packing-list'
      fullPath: '/packing-list'
      preLoaderRoute: typeof PackingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecards': {
      id: '/scorecards'
      path: '/scorecards'
      fullPath: '/scorecards'
      preLoaderRoute: typeof ScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slander': {
      id: '/slander'
      path: '/slander'
      fullPath: '/slander'
      preLoaderRoute: typeof SlanderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CoursesRoute: CoursesRoute,
  DrawRoute: DrawRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PackingListRoute: PackingListRoute,
  ScorecardsRoute: ScorecardsRoute,
  ScoresRoute: ScoresRoute,
  SlanderRoute: SlanderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
